name: agwork
description: Mobile app for AG course.
version: 1.0.0+1

environment:
    sdk: ">=2.19.2"

dependencies:
    flutter:
        sdk: flutter

    flutter_map: ^3.1.0
    cupertino_icons: ^1.0.0

    equatable: ^2.0.5
    flutter_bloc: ^8.1.2

    build_runner: ^2.3.3
    json_serializable: ^6.6.1

    shared_preferences: ^2.0.17

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true