name: ag_work
description: Mobile app for AG course.
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    flutter_map: ^0.10.1+1
    cupertino_icons: ^1.0.0

    equatable: ^1.2.5
    flutter_bloc: ^6.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true